In [1]:
import pandas as pd
import sklearn
import numpy as np 


In [2]:
from pandas.compat import StringIO

In [3]:
#rad the realative path for the data to be read then us panda to store 
path=(r'C:\Users\amit\Desktop\amit\sms.tsv')
sms=pd.read_table(path,header=None,names=['label','message'],)

In [4]:
#online directory
#url='https://github.com/justmarkham/pycon-2016-tutorial/blob/master/data/sms.tsv'
#sms=pd.read_table(url,header=None,names=['label','message'])

In [5]:
sms.shape

(5572, 2)

In [6]:
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [7]:
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [8]:
sms['label'].head().values

array(['ham', 'ham', 'spam', 'ham', 'ham'], dtype=object)

In [9]:
#convert the lable data to structure 
sms['label_num']= sms.label.map ({'ham':0},{'spam':1}).fillna(1).astype(int)
#np.where(np.isnan(sms['label_num']))
#np.nan_to_num({1})

In [10]:
import numpy as np
#sms = sms.replace(np.nan, '', regex=True)

In [11]:
sms.head(10)

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0
5  spam  FreeMsg Hey there darling it's been 3 week's n...          1
6   ham  Even my brother is not like to speak with me. ...          0
7   ham  As per your request 'Melle Melle (Oru Minnamin...          0
8  spam  WINNER!! As a valued network customer you have...          1
9  spam  Had your mobile 11 months or more? U R entitle...          1

In [12]:
X=sms.message
y=sms.label_num
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [13]:
sms['message'].head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: message, dtype: object

In [14]:
#split the test for the train test split
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4179,)
(1393,)
(4179,)
(1393,)


C:\Users\amit\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [15]:
#now we will vectorize our datasets 

In [16]:
#instantiate the count vectorizer
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()

In [17]:
#now learn the vocabulory by training data and used it 
#vect.fit(X_train)
#X_train_dtm=vect.transform(X_train)

In [18]:
#you can even do above term into the single call called fit_transform jus for knowledge little bit faster than above and use inRW
X_train_dtm=vect.fit_transform(X_train.astype(str))

In [19]:
X_train_dtm

<4179x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [20]:
X_test_dtm=vect.transform(X_test.astype(str))
X_test_dtm

<1393x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

In [21]:
#start the model base design 

In [22]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [23]:
%time nb.fit(X_train_dtm,y_train)

Wall time: 482 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [24]:
#now make x_test_predictions 
y_predict_class=nb.predict(X_test_dtm)

In [25]:
#now calculate the prediction accuracy 
from sklearn import metrics
metrics.accuracy_score(y_test,y_predict_class)

0.9885139985642498

In [26]:
metrics.confusion_matrix(y_test,y_predict_class)

array([[1203,    5],
       [  11,  174]], dtype=int64)

In [27]:
#print the mesg which is false positive 
X_test[y_predict_class > y_test]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [28]:
#false negative 
X_test[y_predict_class < y_test]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: message, dtype: object

In [29]:
# now we lets see the probality of the x_test_dtm
nb.predict_proba(X_test_dtm)

array([[9.97122551e-01, 2.87744864e-03],
       [9.99981651e-01, 1.83488846e-05],
       [9.97926987e-01, 2.07301295e-03],
       ...,
       [9.99998910e-01, 1.09026171e-06],
       [1.86697467e-10, 1.00000000e+00],
       [9.99999996e-01, 3.98279868e-09]])

In [30]:
#calculated predicted probality of the now as we want only y value of y test so 
y_pred_prob=nb.predict_proba(X_test_dtm)[:,1]
y_pred_prob

array([2.87744864e-03, 1.83488846e-05, 2.07301295e-03, ...,
       1.09026171e-06, 1.00000000e+00, 3.98279868e-09])

In [31]:
metrics.roc_auc_score(y_test,y_pred_prob)

0.9866431000536962

In [32]:
#now lets compare model to the logistic regression 

In [33]:
from sklearn.linear_model import LogisticRegression 
log_reg=LogisticRegression()

In [34]:
%time log_reg.fit(X_train_dtm,y_train)

Wall time: 584 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
#make class prediction of the x_train_dtm
y_pred_class=log_reg.predict(X_test_dtm)


In [36]:
#now the next step is to check the probabilty of the prediction class (we nwant to used the all row n 1st column so we use[:,1])
y_pred_prob=log_reg.predict_proba(X_train_dtm)[:,1]
y_pred_prob

array([0.99295512, 0.00812153, 0.99279659, ..., 0.00940407, 0.98601086,
       0.08007832])

In [37]:
#now calculate the predicted accuracy
metrics.accuracy_score(y_test,y_pred_class)

0.9877961234745154

In [38]:
#examine teh model for the further test
X_train_token=vect.get_feature_names()
len(X_train_token)

7456

In [39]:
#examine the train token first
print(X_train_token[:50])

['00', '000', '008704050406', '0121', '01223585236', '01223585334', '0125698789', '02', '0207', '02072069400', '02073162414', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07090201529', '07090298926', '07123456789', '07732584351', '07734396839', '07742676969', '0776xxxxxxx', '07781482378', '07786200117', '078', '07801543489', '07808', '07808247860', '07808726822', '07815296484', '07821230901', '07880867867', '0789xxxxxxx', '07946746291', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705']


In [40]:
#examine the last token 
print(X_train_token[-50:])

['yer', 'yes', 'yest', 'yesterday', 'yet', 'yetunde', 'yijue', 'ym', 'ymca', 'yo', 'yoga', 'yogasana', 'yor', 'yorge', 'you', 'youdoing', 'youi', 'youphone', 'your', 'youre', 'yourjob', 'yours', 'yourself', 'youwanna', 'yowifes', 'yoyyooo', 'yr', 'yrs', 'ything', 'yummmm', 'yummy', 'yun', 'yunny', 'yuo', 'yuou', 'yup', 'zac', 'zaher', 'zealand', 'zebra', 'zed', 'zeros', 'zhong', 'zindgi', 'zoe', 'zoom', 'zouk', 'zyada', 'èn', '〨ud']


In [41]:
#naive bayes will tell you each word will come in teh each class by the feature_
nb.feature_count_

array([[ 0.,  0.,  0., ...,  1.,  1.,  1.],
       [ 5., 23.,  2., ...,  0.,  0.,  0.]])

In [42]:
#now the row represent the words and column represent the tokens
nb.feature_count_.shape

(2, 7456)

In [43]:
#now lets count the all rows of the counts 
ham_token_count=nb.feature_count_[0,:]
ham_token_count

array([0., 0., 0., ..., 1., 1., 1.])

In [44]:
#now lets coun the token count in the spam
spam_token_count=nb.feature_count_[1,:]
spam_token_count

array([ 5., 23.,  2., ...,  0.,  0.,  0.])

In [45]:
#now create the spam and ham token count as in table
tokens=pd.DataFrame({'token':X_train_token,'ham':ham_token_count,'spam':spam_token_count})
tokens.head()

ham  spam         token
0  0.0   5.0            00
1  0.0  23.0           000
2  0.0   2.0  008704050406
3  0.0   1.0          0121
4  0.0   1.0   01223585236

In [46]:
#now we will get the info of the sample with pandas
tokens.sample(5,random_state=6)

ham  spam         token
6977  64.0   2.0          very
4521   1.0   1.0         nasty
6999   0.0   1.0         villa
1266   1.0   0.0       beloved
6522   0.0   2.0  textoperator

In [47]:
#nive bayes classification for the sample
nb.class_count_

array([3617.,  562.])

In [48]:
#now add 1 to ham and spam so that it will not confuse the by dividing the 0 rows
tokens['ham']=tokens.ham+1
tokens['spam']=tokens.spam+1
tokens.sample(5,random_state=6)

ham  spam         token
6977  65.0   3.0          very
4521   2.0   2.0         nasty
6999   1.0   2.0         villa
1266   2.0   1.0       beloved
6522   1.0   3.0  textoperator

In [49]:
#this will convert to the frequency 
tokens['ham']=tokens.ham/nb.class_count_[0]
tokens['spam']=tokens.spam/nb.class_count_[1]
tokens.sample(5,random_state=6)

ham      spam         token
6977  0.017971  0.005338          very
4521  0.000553  0.003559         nasty
6999  0.000276  0.003559         villa
1266  0.000553  0.001779       beloved
6522  0.000276  0.005338  textoperator

In [50]:
#now we are into almost last stage now just we will see the ratio of spam to ham
tokens['spam_ratio']=tokens.spam/tokens.ham
tokens.sample(5,random_state=6)

ham      spam         token  spam_ratio
6977  0.017971  0.005338          very    0.297044
4521  0.000553  0.003559         nasty    6.435943
6999  0.000276  0.003559         villa   12.871886
1266  0.000553  0.001779       beloved    3.217972
6522  0.000276  0.005338  textoperator   19.307829

In [51]:
tokens.sort_values('spam_ratio',ascending=False)
tokens.head(5)
#print(tokens['spam_ratio'].head())

ham      spam         token  spam_ratio
0  0.000276  0.010676            00   38.615658
1  0.000276  0.042705           000  154.462633
2  0.000276  0.005338  008704050406   19.307829
3  0.000276  0.003559          0121   12.871886
4  0.000276  0.003559   01223585236   12.871886

In [52]:
#now if you want to know each word spammy ration then 
#tokens.loc['villa','spam_ratio']

KeyError: 'the label [villa] is not in the [index]'